apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - credentials.yaml
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in crd/kustomization.yaml
#- ../webhook
# [CERTMANAGER] To enable cert-manager, uncomment next line. 'WEBHOOK' components are required.
#- ../certmanager

bases:
  - ../rbac
  - ../manager
  - ../webhook
  - ../certmanager

patchesStrategicMerge:
  - manager_image_patch.yaml
  - manager_pull_policy.yaml
  - manager_credentials_patch.yaml
  - manager_webhook_patch.yaml
  - webhookcainjection_patch.yaml
    # Protect the /metrics endpoint by putting it behind auth.
    # Only one of manager_auth_proxy_patch.yaml and
    # manager_prometheus_metrics_patch.yaml should be enabled.
    # - manager_auth_proxy_patch.yaml
    # If you want your controller-manager to expose the /metrics
    # endpoint w/o any authn/z, uncomment the following line and
    # comment manager_auth_proxy_patch.yaml.
    # Only one of manager_auth_proxy_patch.yaml and
  # manager_prometheus_metrics_patch.yaml should be enabled.
#- manager_prometheus_metrics_patch.yaml

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in crd/kustomization.yaml
#- manager_webhook_patch.yaml

# [CAINJECTION] Uncomment next line to enable the CA injection in the admission webhooks.
# Uncomment 'CAINJECTION' in crd/kustomization.yaml to enable the CA injection in the admission webhooks.
# 'CERTMANAGER' needs to be enabled to use ca injection
#- webhookcainjection_patch.yaml
vars:
  - name: CERTIFICATE_NAMESPACE # namespace of the certificate CR
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
    fieldref:
      fieldpath: metadata.namespace
  - name: CERTIFICATE_NAME
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
  - name: SERVICE_NAMESPACE # namespace of the service
    objref:
      kind: Service
      version: v1
      name: webhook-service
    fieldref:
      fieldpath: metadata.namespace
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: webhook-service
