/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// LogTarget Per-instance logging of events and traffic.
type LogTarget struct {
	Address  string `json:"address,omitempty"`
	Facility string `json:"facility,omitempty"`
	Format   string `json:"format,omitempty"`
	Global   bool   `json:"global,omitempty"`
	Id       *int32 `json:"id"`
	Length   int32  `json:"length,omitempty"`
	Level    string `json:"level,omitempty"`
	Minlevel string `json:"minlevel,omitempty"`
	Nolog    bool   `json:"nolog,omitempty"`
}
