/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// LogTarget Per-instance logging of events and traffic.
type LogTarget struct {
	Address  string `json:"address,omitempty"`
	Facility string `json:"facility,omitempty"`
	Format   string `json:"format,omitempty"`
	Global   bool   `json:"global,omitempty"`
	Id       *int32 `json:"id"`
	Length   int32  `json:"length,omitempty"`
	Level    string `json:"level,omitempty"`
	Minlevel string `json:"minlevel,omitempty"`
	Nolog    bool   `json:"nolog,omitempty"`
}
