/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Filter HAProxy filters
type Filter struct {
	CacheName          string `json:"cache_name,omitempty"`
	Id                 *int32 `json:"id"`
	SpoeConfig         string `json:"spoe_config,omitempty"`
	SpoeEngine         string `json:"spoe_engine,omitempty"`
	TraceHexdump       bool   `json:"trace_hexdump,omitempty"`
	TraceName          string `json:"trace_name,omitempty"`
	TraceRndForwarding bool   `json:"trace_rnd_forwarding,omitempty"`
	TraceRndParsing    bool   `json:"trace_rnd_parsing,omitempty"`
	Type               string `json:"type"`
}
