/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// TcpResponseRule HAProxy TCP Response Rule configuration (corresponds to tcp-response)
type TcpResponseRule struct {
	Action   string `json:"action,omitempty"`
	Cond     string `json:"cond,omitempty"`
	CondTest string `json:"cond_test,omitempty"`
	Id       *int32 `json:"id"`
	Timeout  *int32 `json:"timeout,omitempty"`
	Type     string `json:"type"`
}
