/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse20018 struct for InlineResponse20018
type InlineResponse20018 struct {
	Version int32 `json:"_version,omitempty"`
	// HAProxy TCP response rules array (corresponds to tcp-response directive)
	Data []TcpResponseRule `json:"data"`
}
