/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Httpchk struct for Httpchk
type Httpchk struct {
	Method  string `json:"method,omitempty"`
	Uri     string `json:"uri,omitempty"`
	Version string `json:"version,omitempty"`
}
