/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse20014 struct for InlineResponse20014
type InlineResponse20014 struct {
	Version int32 `json:"_version,omitempty"`
	// HAProxy HTTP response rules array (corresponds to http-response directives)
	Data []HttpResponseRule `json:"data"`
}
