/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SiteService struct for SiteService
type SiteService struct {
	HttpConnectionMode string `json:"http_connection_mode,omitempty"`
	Listeners          []Bind `json:"listeners,omitempty"`
	Maxconn            *int32 `json:"maxconn,omitempty"`
	Mode               string `json:"mode,omitempty"`
}
