/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Forwardfor struct for Forwardfor
type Forwardfor struct {
	Enabled string `json:"enabled"`
	Except  string `json:"except,omitempty"`
	Header  string `json:"header,omitempty"`
	Ifnone  bool   `json:"ifnone,omitempty"`
}
