/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineResponse20012 struct for InlineResponse20012
type InlineResponse20012 struct {
	Version int32 `json:"_version,omitempty"`
	// HAProxy HTTP request rules array (corresponds to http-request directives)
	Data []HttpRequestRule `json:"data"`
}
