/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Frontend HAProxy frontend configuration
type Frontend struct {
	Clflog               bool        `json:"clflog,omitempty"`
	ClientTimeout        *int32      `json:"client_timeout,omitempty"`
	Clitcpka             string      `json:"clitcpka,omitempty"`
	Contstats            string      `json:"contstats,omitempty"`
	DefaultBackend       string      `json:"default_backend,omitempty"`
	Dontlognull          string      `json:"dontlognull,omitempty"`
	Forwardfor           *Forwardfor `json:"forwardfor,omitempty"`
	HttpUseHtx           string      `json:"http-use-htx,omitempty"`
	HttpConnectionMode   string      `json:"http_connection_mode,omitempty"`
	HttpKeepAliveTimeout *int32      `json:"http_keep_alive_timeout,omitempty"`
	HttpRequestTimeout   *int32      `json:"http_request_timeout,omitempty"`
	Httplog              bool        `json:"httplog,omitempty"`
	LogFormat            string      `json:"log_format,omitempty"`
	LogFormatSd          string      `json:"log_format_sd,omitempty"`
	LogSeparateErrors    string      `json:"log_separate_errors,omitempty"`
	LogTag               string      `json:"log_tag,omitempty"`
	Maxconn              *int32      `json:"maxconn,omitempty"`
	Mode                 string      `json:"mode,omitempty"`
	Name                 string      `json:"name"`
	Tcplog               bool        `json:"tcplog,omitempty"`
}
