/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Server HAProxy backend server configuration
type Server struct {
	Address        string `json:"address,omitempty"`
	Backup         string `json:"backup,omitempty"`
	Check          string `json:"check,omitempty"`
	Cookie         string `json:"cookie,omitempty"`
	Inter          *int32 `json:"inter,omitempty"`
	Maintenance    string `json:"maintenance,omitempty"`
	Maxconn        *int32 `json:"maxconn,omitempty"`
	Name           string `json:"name"`
	OnError        string `json:"on-error,omitempty"`
	OnMarkedDown   string `json:"on-marked-down,omitempty"`
	OnMarkedUp     string `json:"on-marked-up,omitempty"`
	Port           *int32 `json:"port,omitempty"`
	Ssl            string `json:"ssl,omitempty"`
	SslCafile      string `json:"ssl_cafile,omitempty"`
	SslCertificate string `json:"ssl_certificate,omitempty"`
	TlsTickets     string `json:"tls_tickets,omitempty"`
	Verify         string `json:"verify,omitempty"`
	Weight         *int32 `json:"weight,omitempty"`
}
