/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Backend HAProxy backend configuration
type Backend struct {
	AdvCheck             string             `json:"adv_check,omitempty"`
	Balance              Balance            `json:"balance,omitempty"`
	CheckTimeout         *int32             `json:"check_timeout,omitempty"`
	ConnectTimeout       *int32             `json:"connect_timeout,omitempty"`
	Cookie               string             `json:"cookie,omitempty"`
	DefaultServer        *DefaultServer     `json:"default_server,omitempty"`
	ExternalCheck        string             `json:"external_check,omitempty"`
	ExternalCheckCommand string             `json:"external_check_command,omitempty"`
	ExternalCheckPath    string             `json:"external_check_path,omitempty"`
	Forwardfor           *Forwardfor        `json:"forwardfor,omitempty"`
	HashType             *BackendHashType   `json:"hash_type,omitempty"`
	HttpUseHtx           string             `json:"http-use-htx,omitempty"`
	HttpConnectionMode   string             `json:"http_connection_mode,omitempty"`
	HttpKeepAliveTimeout *int32             `json:"http_keep_alive_timeout,omitempty"`
	HttpPretendKeepalive string             `json:"http_pretend_keepalive,omitempty"`
	HttpRequestTimeout   *int32             `json:"http_request_timeout,omitempty"`
	Httpchk              *Httpchk           `json:"httpchk,omitempty"`
	LogTag               string             `json:"log_tag,omitempty"`
	Mode                 string             `json:"mode,omitempty"`
	Name                 string             `json:"name"`
	QueueTimeout         *int32             `json:"queue_timeout,omitempty"`
	Redispatch           *Redispatch        `json:"redispatch,omitempty"`
	Retries              *int32             `json:"retries,omitempty"`
	ServerTimeout        *int32             `json:"server_timeout,omitempty"`
	StickTable           *BackendStickTable `json:"stick_table,omitempty"`
}
