/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Endpoint Endpoint definition
type Endpoint struct {
	// Endpoint description
	Description string `json:"description,omitempty"`
	// Endpoint title
	Title string `json:"title,omitempty"`
	// Path to the endpoint
	Url string `json:"url,omitempty"`
}
