/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Reload HAProxy reload
type Reload struct {
	Id              string `json:"id,omitempty"`
	ReloadTimestamp int32  `json:"reload_timestamp,omitempty"`
	Response        string `json:"response,omitempty"`
	Status          string `json:"status,omitempty"`
}
