/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NativeStat Current stats for one object.
type NativeStat struct {
	BackendName string          `json:"backend_name,omitempty"`
	Name        string          `json:"name,omitempty"`
	Stats       NativeStatStats `json:"stats,omitempty"`
	Type        string          `json:"type,omitempty"`
}
