/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GlobalRuntimeApis struct for GlobalRuntimeApis
type GlobalRuntimeApis struct {
	Address           string `json:"address"`
	ExposeFdListeners bool   `json:"exposeFdListeners,omitempty"`
	Level             string `json:"level,omitempty"`
	Mode              string `json:"mode,omitempty"`
	Process           string `json:"process,omitempty"`
}
