/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InfoSystemCpuInfo struct for InfoSystemCpuInfo
type InfoSystemCpuInfo struct {
	Model string `json:"model,omitempty"`
	// Number of logical CPUs
	NumCpus int32 `json:"num_cpus,omitempty"`
}
