/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GlobalCpuMaps struct for GlobalCpuMaps
type GlobalCpuMaps struct {
	CpuSet  string `json:"cpu_set"`
	Process string `json:"process"`
}
