/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 1.2
 * Contact: support@haproxy.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// InfoApi struct for InfoApi
type InfoApi struct {
	// HAProxy Dataplane API build date
	BuildDate time.Time `json:"build_date,omitempty"`
	// HAProxy Dataplane API version string
	Version string `json:"version,omitempty"`
}
