run:
  timeout: 10m
  go: "1.21"
  skip-files:
  - ".*zz_generated.*\\.go"
  - "contrib/.*"
  - "apis/v1alpha3/.*"
  - "apis/v1alpha4/.*"
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
  - asciicheck
  - bodyclose
  - dogsled
  - errcheck
  - exportloopref
  - gci
  - goconst
  - gocritic
  - gocyclo
  - godot
  - gofmt
  - goimports
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - misspell
  - nakedret
  - nilerr
  - noctx
  - nolintlint
  - prealloc
  - predeclared
  - revive
  - rowserrcheck
  - staticcheck
  - stylecheck
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace

linters-settings:
  gci:
    local-prefixes: sigs.k8s.io/cluster-api-provider-vsphere
issue:
  max-same-issues: 0
  max-per-linter: 0
issues:
  exclude-rules:
    - path: "test/e2e/*"
      linters:
        - gosec
      text: "G106:"
    - linters:
        - revive
      text: "dot-imports"
      path: ".*test.*"
    - linters:
        - stylecheck
      text: "ST1001"
      path: ".*test.*"
