version: v2.1.0
name: golangci-lint-kube-api-linter
destination: ./bin
plugins:
  - module: 'sigs.k8s.io/kube-api-linter'
    path: ../../../kube-api-linter
    # using JoelSpeed/required-fields-v2 branch for now
