apiVersion: apps/v1
kind: Deployment
metadata:
  name: capv-controller-manager
  namespace: capv-system
spec:
  template:
    spec:
      containers:
      - name: manager
        image: ${CAPV_MANAGER_IMAGE}
        args:
        - --enable-leader-election
        - --logtostderr
        - --v=${CAPV_MANAGER_LOG_LEVEL}
