// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha2

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1alpha3 "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha3"
	apiv1alpha3 "sigs.k8s.io/cluster-api/api/v1alpha3"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*APIEndpoint)(nil), (*v1alpha3.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_APIEndpoint_To_v1alpha3_APIEndpoint(a.(*APIEndpoint), b.(*v1alpha3.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.APIEndpoint)(nil), (*APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_APIEndpoint_To_v1alpha2_APIEndpoint(a.(*v1alpha3.APIEndpoint), b.(*APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CPIConfig)(nil), (*v1alpha3.CPIConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CPIConfig_To_v1alpha3_CPIConfig(a.(*CPIConfig), b.(*v1alpha3.CPIConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.CPIConfig)(nil), (*CPIConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_CPIConfig_To_v1alpha2_CPIConfig(a.(*v1alpha3.CPIConfig), b.(*CPIConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CPIDiskConfig)(nil), (*v1alpha3.CPIDiskConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CPIDiskConfig_To_v1alpha3_CPIDiskConfig(a.(*CPIDiskConfig), b.(*v1alpha3.CPIDiskConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.CPIDiskConfig)(nil), (*CPIDiskConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_CPIDiskConfig_To_v1alpha2_CPIDiskConfig(a.(*v1alpha3.CPIDiskConfig), b.(*CPIDiskConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CPIGlobalConfig)(nil), (*v1alpha3.CPIGlobalConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CPIGlobalConfig_To_v1alpha3_CPIGlobalConfig(a.(*CPIGlobalConfig), b.(*v1alpha3.CPIGlobalConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.CPIGlobalConfig)(nil), (*CPIGlobalConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_CPIGlobalConfig_To_v1alpha2_CPIGlobalConfig(a.(*v1alpha3.CPIGlobalConfig), b.(*CPIGlobalConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CPILabelConfig)(nil), (*v1alpha3.CPILabelConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CPILabelConfig_To_v1alpha3_CPILabelConfig(a.(*CPILabelConfig), b.(*v1alpha3.CPILabelConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.CPILabelConfig)(nil), (*CPILabelConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_CPILabelConfig_To_v1alpha2_CPILabelConfig(a.(*v1alpha3.CPILabelConfig), b.(*CPILabelConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CPINetworkConfig)(nil), (*v1alpha3.CPINetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CPINetworkConfig_To_v1alpha3_CPINetworkConfig(a.(*CPINetworkConfig), b.(*v1alpha3.CPINetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.CPINetworkConfig)(nil), (*CPINetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_CPINetworkConfig_To_v1alpha2_CPINetworkConfig(a.(*v1alpha3.CPINetworkConfig), b.(*CPINetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CPIProviderConfig)(nil), (*v1alpha3.CPIProviderConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CPIProviderConfig_To_v1alpha3_CPIProviderConfig(a.(*CPIProviderConfig), b.(*v1alpha3.CPIProviderConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.CPIProviderConfig)(nil), (*CPIProviderConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_CPIProviderConfig_To_v1alpha2_CPIProviderConfig(a.(*v1alpha3.CPIProviderConfig), b.(*CPIProviderConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CPIStorageConfig)(nil), (*v1alpha3.CPIStorageConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CPIStorageConfig_To_v1alpha3_CPIStorageConfig(a.(*CPIStorageConfig), b.(*v1alpha3.CPIStorageConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.CPIStorageConfig)(nil), (*CPIStorageConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_CPIStorageConfig_To_v1alpha2_CPIStorageConfig(a.(*v1alpha3.CPIStorageConfig), b.(*CPIStorageConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CPIVCenterConfig)(nil), (*v1alpha3.CPIVCenterConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CPIVCenterConfig_To_v1alpha3_CPIVCenterConfig(a.(*CPIVCenterConfig), b.(*v1alpha3.CPIVCenterConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.CPIVCenterConfig)(nil), (*CPIVCenterConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_CPIVCenterConfig_To_v1alpha2_CPIVCenterConfig(a.(*v1alpha3.CPIVCenterConfig), b.(*CPIVCenterConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CPIWorkspaceConfig)(nil), (*v1alpha3.CPIWorkspaceConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CPIWorkspaceConfig_To_v1alpha3_CPIWorkspaceConfig(a.(*CPIWorkspaceConfig), b.(*v1alpha3.CPIWorkspaceConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.CPIWorkspaceConfig)(nil), (*CPIWorkspaceConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_CPIWorkspaceConfig_To_v1alpha2_CPIWorkspaceConfig(a.(*v1alpha3.CPIWorkspaceConfig), b.(*CPIWorkspaceConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkDeviceSpec)(nil), (*v1alpha3.NetworkDeviceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkDeviceSpec_To_v1alpha3_NetworkDeviceSpec(a.(*NetworkDeviceSpec), b.(*v1alpha3.NetworkDeviceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.NetworkDeviceSpec)(nil), (*NetworkDeviceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_NetworkDeviceSpec_To_v1alpha2_NetworkDeviceSpec(a.(*v1alpha3.NetworkDeviceSpec), b.(*NetworkDeviceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkRouteSpec)(nil), (*v1alpha3.NetworkRouteSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkRouteSpec_To_v1alpha3_NetworkRouteSpec(a.(*NetworkRouteSpec), b.(*v1alpha3.NetworkRouteSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.NetworkRouteSpec)(nil), (*NetworkRouteSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_NetworkRouteSpec_To_v1alpha2_NetworkRouteSpec(a.(*v1alpha3.NetworkRouteSpec), b.(*NetworkRouteSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkSpec)(nil), (*v1alpha3.NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkSpec_To_v1alpha3_NetworkSpec(a.(*NetworkSpec), b.(*v1alpha3.NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.NetworkSpec)(nil), (*NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_NetworkSpec_To_v1alpha2_NetworkSpec(a.(*v1alpha3.NetworkSpec), b.(*NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkStatus)(nil), (*v1alpha3.NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkStatus_To_v1alpha3_NetworkStatus(a.(*NetworkStatus), b.(*v1alpha3.NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.NetworkStatus)(nil), (*NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_NetworkStatus_To_v1alpha2_NetworkStatus(a.(*v1alpha3.NetworkStatus), b.(*NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VSphereCluster)(nil), (*v1alpha3.VSphereCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VSphereCluster_To_v1alpha3_VSphereCluster(a.(*VSphereCluster), b.(*v1alpha3.VSphereCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.VSphereCluster)(nil), (*VSphereCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VSphereCluster_To_v1alpha2_VSphereCluster(a.(*v1alpha3.VSphereCluster), b.(*VSphereCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VSphereClusterList)(nil), (*v1alpha3.VSphereClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VSphereClusterList_To_v1alpha3_VSphereClusterList(a.(*VSphereClusterList), b.(*v1alpha3.VSphereClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.VSphereClusterList)(nil), (*VSphereClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VSphereClusterList_To_v1alpha2_VSphereClusterList(a.(*v1alpha3.VSphereClusterList), b.(*VSphereClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VSphereClusterSpec)(nil), (*v1alpha3.VSphereClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VSphereClusterSpec_To_v1alpha3_VSphereClusterSpec(a.(*VSphereClusterSpec), b.(*v1alpha3.VSphereClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VSphereMachine)(nil), (*v1alpha3.VSphereMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VSphereMachine_To_v1alpha3_VSphereMachine(a.(*VSphereMachine), b.(*v1alpha3.VSphereMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.VSphereMachine)(nil), (*VSphereMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VSphereMachine_To_v1alpha2_VSphereMachine(a.(*v1alpha3.VSphereMachine), b.(*VSphereMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VSphereMachineList)(nil), (*v1alpha3.VSphereMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VSphereMachineList_To_v1alpha3_VSphereMachineList(a.(*VSphereMachineList), b.(*v1alpha3.VSphereMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.VSphereMachineList)(nil), (*VSphereMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VSphereMachineList_To_v1alpha2_VSphereMachineList(a.(*v1alpha3.VSphereMachineList), b.(*VSphereMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VSphereMachineTemplate)(nil), (*v1alpha3.VSphereMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VSphereMachineTemplate_To_v1alpha3_VSphereMachineTemplate(a.(*VSphereMachineTemplate), b.(*v1alpha3.VSphereMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.VSphereMachineTemplate)(nil), (*VSphereMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VSphereMachineTemplate_To_v1alpha2_VSphereMachineTemplate(a.(*v1alpha3.VSphereMachineTemplate), b.(*VSphereMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VSphereMachineTemplateList)(nil), (*v1alpha3.VSphereMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VSphereMachineTemplateList_To_v1alpha3_VSphereMachineTemplateList(a.(*VSphereMachineTemplateList), b.(*v1alpha3.VSphereMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.VSphereMachineTemplateList)(nil), (*VSphereMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VSphereMachineTemplateList_To_v1alpha2_VSphereMachineTemplateList(a.(*v1alpha3.VSphereMachineTemplateList), b.(*VSphereMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.VSphereMachineTemplateResource)(nil), (*VSphereMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VSphereMachineTemplateResource_To_v1alpha2_VSphereMachineTemplateResource(a.(*v1alpha3.VSphereMachineTemplateResource), b.(*VSphereMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VSphereMachineTemplateSpec)(nil), (*v1alpha3.VSphereMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VSphereMachineTemplateSpec_To_v1alpha3_VSphereMachineTemplateSpec(a.(*VSphereMachineTemplateSpec), b.(*v1alpha3.VSphereMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.VSphereMachineTemplateSpec)(nil), (*VSphereMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VSphereMachineTemplateSpec_To_v1alpha2_VSphereMachineTemplateSpec(a.(*v1alpha3.VSphereMachineTemplateSpec), b.(*VSphereMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachine)(nil), (*v1alpha3.VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VirtualMachine_To_v1alpha3_VirtualMachine(a.(*VirtualMachine), b.(*v1alpha3.VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.VirtualMachine)(nil), (*VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VirtualMachine_To_v1alpha2_VirtualMachine(a.(*v1alpha3.VirtualMachine), b.(*VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*CPICloudConfig)(nil), (*v1alpha3.CPICloudConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CPICloudConfig_To_v1alpha3_CPICloudConfig(a.(*CPICloudConfig), b.(*v1alpha3.CPICloudConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*VSphereClusterStatus)(nil), (*v1alpha3.VSphereClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VSphereClusterStatus_To_v1alpha3_VSphereClusterStatus(a.(*VSphereClusterStatus), b.(*v1alpha3.VSphereClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*VSphereMachineSpec)(nil), (*v1alpha3.VSphereMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VSphereMachineSpec_To_v1alpha3_VSphereMachineSpec(a.(*VSphereMachineSpec), b.(*v1alpha3.VSphereMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*VSphereMachineStatus)(nil), (*v1alpha3.VSphereMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VSphereMachineStatus_To_v1alpha3_VSphereMachineStatus(a.(*VSphereMachineStatus), b.(*v1alpha3.VSphereMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*VSphereMachineTemplateResource)(nil), (*v1alpha3.VSphereMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VSphereMachineTemplateResource_To_v1alpha3_VSphereMachineTemplateResource(a.(*VSphereMachineTemplateResource), b.(*v1alpha3.VSphereMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha3.CPICloudConfig)(nil), (*CPICloudConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_CPICloudConfig_To_v1alpha2_CPICloudConfig(a.(*v1alpha3.CPICloudConfig), b.(*CPICloudConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha3.VSphereClusterSpec)(nil), (*VSphereClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VSphereClusterSpec_To_v1alpha2_VSphereClusterSpec(a.(*v1alpha3.VSphereClusterSpec), b.(*VSphereClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha3.VSphereClusterStatus)(nil), (*VSphereClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VSphereClusterStatus_To_v1alpha2_VSphereClusterStatus(a.(*v1alpha3.VSphereClusterStatus), b.(*VSphereClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha3.VSphereMachineSpec)(nil), (*VSphereMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VSphereMachineSpec_To_v1alpha2_VSphereMachineSpec(a.(*v1alpha3.VSphereMachineSpec), b.(*VSphereMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha3.VSphereMachineStatus)(nil), (*VSphereMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VSphereMachineStatus_To_v1alpha2_VSphereMachineStatus(a.(*v1alpha3.VSphereMachineStatus), b.(*VSphereMachineStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_APIEndpoint_To_v1alpha3_APIEndpoint(in *APIEndpoint, out *v1alpha3.APIEndpoint, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = int32(in.Port)
	return nil
}

// Convert_v1alpha2_APIEndpoint_To_v1alpha3_APIEndpoint is an autogenerated conversion function.
func Convert_v1alpha2_APIEndpoint_To_v1alpha3_APIEndpoint(in *APIEndpoint, out *v1alpha3.APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1alpha2_APIEndpoint_To_v1alpha3_APIEndpoint(in, out, s)
}

func autoConvert_v1alpha3_APIEndpoint_To_v1alpha2_APIEndpoint(in *v1alpha3.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = int(in.Port)
	return nil
}

// Convert_v1alpha3_APIEndpoint_To_v1alpha2_APIEndpoint is an autogenerated conversion function.
func Convert_v1alpha3_APIEndpoint_To_v1alpha2_APIEndpoint(in *v1alpha3.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1alpha3_APIEndpoint_To_v1alpha2_APIEndpoint(in, out, s)
}

func autoConvert_v1alpha2_CPICloudConfig_To_v1alpha3_CPICloudConfig(in *CPICloudConfig, out *v1alpha3.CPICloudConfig, s conversion.Scope) error {
	out.ControllerImage = in.ControllerImage
	return nil
}

func autoConvert_v1alpha3_CPICloudConfig_To_v1alpha2_CPICloudConfig(in *v1alpha3.CPICloudConfig, out *CPICloudConfig, s conversion.Scope) error {
	out.ControllerImage = in.ControllerImage
	// WARNING: in.ExtraArgs requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha2_CPIConfig_To_v1alpha3_CPIConfig(in *CPIConfig, out *v1alpha3.CPIConfig, s conversion.Scope) error {
	if err := Convert_v1alpha2_CPIGlobalConfig_To_v1alpha3_CPIGlobalConfig(&in.Global, &out.Global, s); err != nil {
		return err
	}
	out.VCenter = *(*map[string]v1alpha3.CPIVCenterConfig)(unsafe.Pointer(&in.VCenter))
	if err := Convert_v1alpha2_CPINetworkConfig_To_v1alpha3_CPINetworkConfig(&in.Network, &out.Network, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_CPIDiskConfig_To_v1alpha3_CPIDiskConfig(&in.Disk, &out.Disk, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_CPIWorkspaceConfig_To_v1alpha3_CPIWorkspaceConfig(&in.Workspace, &out.Workspace, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_CPILabelConfig_To_v1alpha3_CPILabelConfig(&in.Labels, &out.Labels, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_CPIProviderConfig_To_v1alpha3_CPIProviderConfig(&in.ProviderConfig, &out.ProviderConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_CPIConfig_To_v1alpha3_CPIConfig is an autogenerated conversion function.
func Convert_v1alpha2_CPIConfig_To_v1alpha3_CPIConfig(in *CPIConfig, out *v1alpha3.CPIConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_CPIConfig_To_v1alpha3_CPIConfig(in, out, s)
}

func autoConvert_v1alpha3_CPIConfig_To_v1alpha2_CPIConfig(in *v1alpha3.CPIConfig, out *CPIConfig, s conversion.Scope) error {
	if err := Convert_v1alpha3_CPIGlobalConfig_To_v1alpha2_CPIGlobalConfig(&in.Global, &out.Global, s); err != nil {
		return err
	}
	out.VCenter = *(*map[string]CPIVCenterConfig)(unsafe.Pointer(&in.VCenter))
	if err := Convert_v1alpha3_CPINetworkConfig_To_v1alpha2_CPINetworkConfig(&in.Network, &out.Network, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_CPIDiskConfig_To_v1alpha2_CPIDiskConfig(&in.Disk, &out.Disk, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_CPIWorkspaceConfig_To_v1alpha2_CPIWorkspaceConfig(&in.Workspace, &out.Workspace, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_CPILabelConfig_To_v1alpha2_CPILabelConfig(&in.Labels, &out.Labels, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_CPIProviderConfig_To_v1alpha2_CPIProviderConfig(&in.ProviderConfig, &out.ProviderConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_CPIConfig_To_v1alpha2_CPIConfig is an autogenerated conversion function.
func Convert_v1alpha3_CPIConfig_To_v1alpha2_CPIConfig(in *v1alpha3.CPIConfig, out *CPIConfig, s conversion.Scope) error {
	return autoConvert_v1alpha3_CPIConfig_To_v1alpha2_CPIConfig(in, out, s)
}

func autoConvert_v1alpha2_CPIDiskConfig_To_v1alpha3_CPIDiskConfig(in *CPIDiskConfig, out *v1alpha3.CPIDiskConfig, s conversion.Scope) error {
	out.SCSIControllerType = in.SCSIControllerType
	return nil
}

// Convert_v1alpha2_CPIDiskConfig_To_v1alpha3_CPIDiskConfig is an autogenerated conversion function.
func Convert_v1alpha2_CPIDiskConfig_To_v1alpha3_CPIDiskConfig(in *CPIDiskConfig, out *v1alpha3.CPIDiskConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_CPIDiskConfig_To_v1alpha3_CPIDiskConfig(in, out, s)
}

func autoConvert_v1alpha3_CPIDiskConfig_To_v1alpha2_CPIDiskConfig(in *v1alpha3.CPIDiskConfig, out *CPIDiskConfig, s conversion.Scope) error {
	out.SCSIControllerType = in.SCSIControllerType
	return nil
}

// Convert_v1alpha3_CPIDiskConfig_To_v1alpha2_CPIDiskConfig is an autogenerated conversion function.
func Convert_v1alpha3_CPIDiskConfig_To_v1alpha2_CPIDiskConfig(in *v1alpha3.CPIDiskConfig, out *CPIDiskConfig, s conversion.Scope) error {
	return autoConvert_v1alpha3_CPIDiskConfig_To_v1alpha2_CPIDiskConfig(in, out, s)
}

func autoConvert_v1alpha2_CPIGlobalConfig_To_v1alpha3_CPIGlobalConfig(in *CPIGlobalConfig, out *v1alpha3.CPIGlobalConfig, s conversion.Scope) error {
	out.Insecure = in.Insecure
	out.RoundTripperCount = in.RoundTripperCount
	out.Username = in.Username
	out.Password = in.Password
	out.SecretName = in.SecretName
	out.SecretNamespace = in.SecretNamespace
	out.Port = in.Port
	out.CAFile = in.CAFile
	out.Thumbprint = in.Thumbprint
	out.Datacenters = in.Datacenters
	out.ServiceAccount = in.ServiceAccount
	out.SecretsDirectory = in.SecretsDirectory
	out.APIDisable = (*bool)(unsafe.Pointer(in.APIDisable))
	out.APIBindPort = in.APIBindPort
	out.ClusterID = in.ClusterID
	return nil
}

// Convert_v1alpha2_CPIGlobalConfig_To_v1alpha3_CPIGlobalConfig is an autogenerated conversion function.
func Convert_v1alpha2_CPIGlobalConfig_To_v1alpha3_CPIGlobalConfig(in *CPIGlobalConfig, out *v1alpha3.CPIGlobalConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_CPIGlobalConfig_To_v1alpha3_CPIGlobalConfig(in, out, s)
}

func autoConvert_v1alpha3_CPIGlobalConfig_To_v1alpha2_CPIGlobalConfig(in *v1alpha3.CPIGlobalConfig, out *CPIGlobalConfig, s conversion.Scope) error {
	out.Insecure = in.Insecure
	out.RoundTripperCount = in.RoundTripperCount
	out.Username = in.Username
	out.Password = in.Password
	out.SecretName = in.SecretName
	out.SecretNamespace = in.SecretNamespace
	out.Port = in.Port
	out.CAFile = in.CAFile
	out.Thumbprint = in.Thumbprint
	out.Datacenters = in.Datacenters
	out.ServiceAccount = in.ServiceAccount
	out.SecretsDirectory = in.SecretsDirectory
	out.APIDisable = (*bool)(unsafe.Pointer(in.APIDisable))
	out.APIBindPort = in.APIBindPort
	out.ClusterID = in.ClusterID
	return nil
}

// Convert_v1alpha3_CPIGlobalConfig_To_v1alpha2_CPIGlobalConfig is an autogenerated conversion function.
func Convert_v1alpha3_CPIGlobalConfig_To_v1alpha2_CPIGlobalConfig(in *v1alpha3.CPIGlobalConfig, out *CPIGlobalConfig, s conversion.Scope) error {
	return autoConvert_v1alpha3_CPIGlobalConfig_To_v1alpha2_CPIGlobalConfig(in, out, s)
}

func autoConvert_v1alpha2_CPILabelConfig_To_v1alpha3_CPILabelConfig(in *CPILabelConfig, out *v1alpha3.CPILabelConfig, s conversion.Scope) error {
	out.Zone = in.Zone
	out.Region = in.Region
	return nil
}

// Convert_v1alpha2_CPILabelConfig_To_v1alpha3_CPILabelConfig is an autogenerated conversion function.
func Convert_v1alpha2_CPILabelConfig_To_v1alpha3_CPILabelConfig(in *CPILabelConfig, out *v1alpha3.CPILabelConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_CPILabelConfig_To_v1alpha3_CPILabelConfig(in, out, s)
}

func autoConvert_v1alpha3_CPILabelConfig_To_v1alpha2_CPILabelConfig(in *v1alpha3.CPILabelConfig, out *CPILabelConfig, s conversion.Scope) error {
	out.Zone = in.Zone
	out.Region = in.Region
	return nil
}

// Convert_v1alpha3_CPILabelConfig_To_v1alpha2_CPILabelConfig is an autogenerated conversion function.
func Convert_v1alpha3_CPILabelConfig_To_v1alpha2_CPILabelConfig(in *v1alpha3.CPILabelConfig, out *CPILabelConfig, s conversion.Scope) error {
	return autoConvert_v1alpha3_CPILabelConfig_To_v1alpha2_CPILabelConfig(in, out, s)
}

func autoConvert_v1alpha2_CPINetworkConfig_To_v1alpha3_CPINetworkConfig(in *CPINetworkConfig, out *v1alpha3.CPINetworkConfig, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha2_CPINetworkConfig_To_v1alpha3_CPINetworkConfig is an autogenerated conversion function.
func Convert_v1alpha2_CPINetworkConfig_To_v1alpha3_CPINetworkConfig(in *CPINetworkConfig, out *v1alpha3.CPINetworkConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_CPINetworkConfig_To_v1alpha3_CPINetworkConfig(in, out, s)
}

func autoConvert_v1alpha3_CPINetworkConfig_To_v1alpha2_CPINetworkConfig(in *v1alpha3.CPINetworkConfig, out *CPINetworkConfig, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha3_CPINetworkConfig_To_v1alpha2_CPINetworkConfig is an autogenerated conversion function.
func Convert_v1alpha3_CPINetworkConfig_To_v1alpha2_CPINetworkConfig(in *v1alpha3.CPINetworkConfig, out *CPINetworkConfig, s conversion.Scope) error {
	return autoConvert_v1alpha3_CPINetworkConfig_To_v1alpha2_CPINetworkConfig(in, out, s)
}

func autoConvert_v1alpha2_CPIProviderConfig_To_v1alpha3_CPIProviderConfig(in *CPIProviderConfig, out *v1alpha3.CPIProviderConfig, s conversion.Scope) error {
	if in.Cloud != nil {
		in, out := &in.Cloud, &out.Cloud
		*out = new(v1alpha3.CPICloudConfig)
		if err := Convert_v1alpha2_CPICloudConfig_To_v1alpha3_CPICloudConfig(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Cloud = nil
	}
	out.Storage = (*v1alpha3.CPIStorageConfig)(unsafe.Pointer(in.Storage))
	return nil
}

// Convert_v1alpha2_CPIProviderConfig_To_v1alpha3_CPIProviderConfig is an autogenerated conversion function.
func Convert_v1alpha2_CPIProviderConfig_To_v1alpha3_CPIProviderConfig(in *CPIProviderConfig, out *v1alpha3.CPIProviderConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_CPIProviderConfig_To_v1alpha3_CPIProviderConfig(in, out, s)
}

func autoConvert_v1alpha3_CPIProviderConfig_To_v1alpha2_CPIProviderConfig(in *v1alpha3.CPIProviderConfig, out *CPIProviderConfig, s conversion.Scope) error {
	if in.Cloud != nil {
		in, out := &in.Cloud, &out.Cloud
		*out = new(CPICloudConfig)
		if err := Convert_v1alpha3_CPICloudConfig_To_v1alpha2_CPICloudConfig(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Cloud = nil
	}
	out.Storage = (*CPIStorageConfig)(unsafe.Pointer(in.Storage))
	return nil
}

// Convert_v1alpha3_CPIProviderConfig_To_v1alpha2_CPIProviderConfig is an autogenerated conversion function.
func Convert_v1alpha3_CPIProviderConfig_To_v1alpha2_CPIProviderConfig(in *v1alpha3.CPIProviderConfig, out *CPIProviderConfig, s conversion.Scope) error {
	return autoConvert_v1alpha3_CPIProviderConfig_To_v1alpha2_CPIProviderConfig(in, out, s)
}

func autoConvert_v1alpha2_CPIStorageConfig_To_v1alpha3_CPIStorageConfig(in *CPIStorageConfig, out *v1alpha3.CPIStorageConfig, s conversion.Scope) error {
	out.ControllerImage = in.ControllerImage
	out.NodeDriverImage = in.NodeDriverImage
	out.AttacherImage = in.AttacherImage
	out.ProvisionerImage = in.ProvisionerImage
	out.MetadataSyncerImage = in.MetadataSyncerImage
	out.LivenessProbeImage = in.LivenessProbeImage
	out.RegistrarImage = in.RegistrarImage
	return nil
}

// Convert_v1alpha2_CPIStorageConfig_To_v1alpha3_CPIStorageConfig is an autogenerated conversion function.
func Convert_v1alpha2_CPIStorageConfig_To_v1alpha3_CPIStorageConfig(in *CPIStorageConfig, out *v1alpha3.CPIStorageConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_CPIStorageConfig_To_v1alpha3_CPIStorageConfig(in, out, s)
}

func autoConvert_v1alpha3_CPIStorageConfig_To_v1alpha2_CPIStorageConfig(in *v1alpha3.CPIStorageConfig, out *CPIStorageConfig, s conversion.Scope) error {
	out.ControllerImage = in.ControllerImage
	out.NodeDriverImage = in.NodeDriverImage
	out.AttacherImage = in.AttacherImage
	out.ProvisionerImage = in.ProvisionerImage
	out.MetadataSyncerImage = in.MetadataSyncerImage
	out.LivenessProbeImage = in.LivenessProbeImage
	out.RegistrarImage = in.RegistrarImage
	return nil
}

// Convert_v1alpha3_CPIStorageConfig_To_v1alpha2_CPIStorageConfig is an autogenerated conversion function.
func Convert_v1alpha3_CPIStorageConfig_To_v1alpha2_CPIStorageConfig(in *v1alpha3.CPIStorageConfig, out *CPIStorageConfig, s conversion.Scope) error {
	return autoConvert_v1alpha3_CPIStorageConfig_To_v1alpha2_CPIStorageConfig(in, out, s)
}

func autoConvert_v1alpha2_CPIVCenterConfig_To_v1alpha3_CPIVCenterConfig(in *CPIVCenterConfig, out *v1alpha3.CPIVCenterConfig, s conversion.Scope) error {
	out.Username = in.Username
	out.Password = in.Password
	out.Port = in.Port
	out.Datacenters = in.Datacenters
	out.RoundTripperCount = in.RoundTripperCount
	out.Thumbprint = in.Thumbprint
	return nil
}

// Convert_v1alpha2_CPIVCenterConfig_To_v1alpha3_CPIVCenterConfig is an autogenerated conversion function.
func Convert_v1alpha2_CPIVCenterConfig_To_v1alpha3_CPIVCenterConfig(in *CPIVCenterConfig, out *v1alpha3.CPIVCenterConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_CPIVCenterConfig_To_v1alpha3_CPIVCenterConfig(in, out, s)
}

func autoConvert_v1alpha3_CPIVCenterConfig_To_v1alpha2_CPIVCenterConfig(in *v1alpha3.CPIVCenterConfig, out *CPIVCenterConfig, s conversion.Scope) error {
	out.Username = in.Username
	out.Password = in.Password
	out.Port = in.Port
	out.Datacenters = in.Datacenters
	out.RoundTripperCount = in.RoundTripperCount
	out.Thumbprint = in.Thumbprint
	return nil
}

// Convert_v1alpha3_CPIVCenterConfig_To_v1alpha2_CPIVCenterConfig is an autogenerated conversion function.
func Convert_v1alpha3_CPIVCenterConfig_To_v1alpha2_CPIVCenterConfig(in *v1alpha3.CPIVCenterConfig, out *CPIVCenterConfig, s conversion.Scope) error {
	return autoConvert_v1alpha3_CPIVCenterConfig_To_v1alpha2_CPIVCenterConfig(in, out, s)
}

func autoConvert_v1alpha2_CPIWorkspaceConfig_To_v1alpha3_CPIWorkspaceConfig(in *CPIWorkspaceConfig, out *v1alpha3.CPIWorkspaceConfig, s conversion.Scope) error {
	out.Server = in.Server
	out.Datacenter = in.Datacenter
	out.Folder = in.Folder
	out.Datastore = in.Datastore
	out.ResourcePool = in.ResourcePool
	return nil
}

// Convert_v1alpha2_CPIWorkspaceConfig_To_v1alpha3_CPIWorkspaceConfig is an autogenerated conversion function.
func Convert_v1alpha2_CPIWorkspaceConfig_To_v1alpha3_CPIWorkspaceConfig(in *CPIWorkspaceConfig, out *v1alpha3.CPIWorkspaceConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_CPIWorkspaceConfig_To_v1alpha3_CPIWorkspaceConfig(in, out, s)
}

func autoConvert_v1alpha3_CPIWorkspaceConfig_To_v1alpha2_CPIWorkspaceConfig(in *v1alpha3.CPIWorkspaceConfig, out *CPIWorkspaceConfig, s conversion.Scope) error {
	out.Server = in.Server
	out.Datacenter = in.Datacenter
	out.Folder = in.Folder
	out.Datastore = in.Datastore
	out.ResourcePool = in.ResourcePool
	return nil
}

// Convert_v1alpha3_CPIWorkspaceConfig_To_v1alpha2_CPIWorkspaceConfig is an autogenerated conversion function.
func Convert_v1alpha3_CPIWorkspaceConfig_To_v1alpha2_CPIWorkspaceConfig(in *v1alpha3.CPIWorkspaceConfig, out *CPIWorkspaceConfig, s conversion.Scope) error {
	return autoConvert_v1alpha3_CPIWorkspaceConfig_To_v1alpha2_CPIWorkspaceConfig(in, out, s)
}

func autoConvert_v1alpha2_NetworkDeviceSpec_To_v1alpha3_NetworkDeviceSpec(in *NetworkDeviceSpec, out *v1alpha3.NetworkDeviceSpec, s conversion.Scope) error {
	out.NetworkName = in.NetworkName
	out.DeviceName = in.DeviceName
	out.DHCP4 = in.DHCP4
	out.DHCP6 = in.DHCP6
	out.Gateway4 = in.Gateway4
	out.Gateway6 = in.Gateway6
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MTU = (*int64)(unsafe.Pointer(in.MTU))
	out.MACAddr = in.MACAddr
	out.Nameservers = *(*[]string)(unsafe.Pointer(&in.Nameservers))
	out.Routes = *(*[]v1alpha3.NetworkRouteSpec)(unsafe.Pointer(&in.Routes))
	out.SearchDomains = *(*[]string)(unsafe.Pointer(&in.SearchDomains))
	return nil
}

// Convert_v1alpha2_NetworkDeviceSpec_To_v1alpha3_NetworkDeviceSpec is an autogenerated conversion function.
func Convert_v1alpha2_NetworkDeviceSpec_To_v1alpha3_NetworkDeviceSpec(in *NetworkDeviceSpec, out *v1alpha3.NetworkDeviceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_NetworkDeviceSpec_To_v1alpha3_NetworkDeviceSpec(in, out, s)
}

func autoConvert_v1alpha3_NetworkDeviceSpec_To_v1alpha2_NetworkDeviceSpec(in *v1alpha3.NetworkDeviceSpec, out *NetworkDeviceSpec, s conversion.Scope) error {
	out.NetworkName = in.NetworkName
	out.DeviceName = in.DeviceName
	out.DHCP4 = in.DHCP4
	out.DHCP6 = in.DHCP6
	out.Gateway4 = in.Gateway4
	out.Gateway6 = in.Gateway6
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MTU = (*int64)(unsafe.Pointer(in.MTU))
	out.MACAddr = in.MACAddr
	out.Nameservers = *(*[]string)(unsafe.Pointer(&in.Nameservers))
	out.Routes = *(*[]NetworkRouteSpec)(unsafe.Pointer(&in.Routes))
	out.SearchDomains = *(*[]string)(unsafe.Pointer(&in.SearchDomains))
	return nil
}

// Convert_v1alpha3_NetworkDeviceSpec_To_v1alpha2_NetworkDeviceSpec is an autogenerated conversion function.
func Convert_v1alpha3_NetworkDeviceSpec_To_v1alpha2_NetworkDeviceSpec(in *v1alpha3.NetworkDeviceSpec, out *NetworkDeviceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_NetworkDeviceSpec_To_v1alpha2_NetworkDeviceSpec(in, out, s)
}

func autoConvert_v1alpha2_NetworkRouteSpec_To_v1alpha3_NetworkRouteSpec(in *NetworkRouteSpec, out *v1alpha3.NetworkRouteSpec, s conversion.Scope) error {
	out.To = in.To
	out.Via = in.Via
	out.Metric = in.Metric
	return nil
}

// Convert_v1alpha2_NetworkRouteSpec_To_v1alpha3_NetworkRouteSpec is an autogenerated conversion function.
func Convert_v1alpha2_NetworkRouteSpec_To_v1alpha3_NetworkRouteSpec(in *NetworkRouteSpec, out *v1alpha3.NetworkRouteSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_NetworkRouteSpec_To_v1alpha3_NetworkRouteSpec(in, out, s)
}

func autoConvert_v1alpha3_NetworkRouteSpec_To_v1alpha2_NetworkRouteSpec(in *v1alpha3.NetworkRouteSpec, out *NetworkRouteSpec, s conversion.Scope) error {
	out.To = in.To
	out.Via = in.Via
	out.Metric = in.Metric
	return nil
}

// Convert_v1alpha3_NetworkRouteSpec_To_v1alpha2_NetworkRouteSpec is an autogenerated conversion function.
func Convert_v1alpha3_NetworkRouteSpec_To_v1alpha2_NetworkRouteSpec(in *v1alpha3.NetworkRouteSpec, out *NetworkRouteSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_NetworkRouteSpec_To_v1alpha2_NetworkRouteSpec(in, out, s)
}

func autoConvert_v1alpha2_NetworkSpec_To_v1alpha3_NetworkSpec(in *NetworkSpec, out *v1alpha3.NetworkSpec, s conversion.Scope) error {
	out.Devices = *(*[]v1alpha3.NetworkDeviceSpec)(unsafe.Pointer(&in.Devices))
	out.Routes = *(*[]v1alpha3.NetworkRouteSpec)(unsafe.Pointer(&in.Routes))
	out.PreferredAPIServerCIDR = in.PreferredAPIServerCIDR
	return nil
}

// Convert_v1alpha2_NetworkSpec_To_v1alpha3_NetworkSpec is an autogenerated conversion function.
func Convert_v1alpha2_NetworkSpec_To_v1alpha3_NetworkSpec(in *NetworkSpec, out *v1alpha3.NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_NetworkSpec_To_v1alpha3_NetworkSpec(in, out, s)
}

func autoConvert_v1alpha3_NetworkSpec_To_v1alpha2_NetworkSpec(in *v1alpha3.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	out.Devices = *(*[]NetworkDeviceSpec)(unsafe.Pointer(&in.Devices))
	out.Routes = *(*[]NetworkRouteSpec)(unsafe.Pointer(&in.Routes))
	out.PreferredAPIServerCIDR = in.PreferredAPIServerCIDR
	return nil
}

// Convert_v1alpha3_NetworkSpec_To_v1alpha2_NetworkSpec is an autogenerated conversion function.
func Convert_v1alpha3_NetworkSpec_To_v1alpha2_NetworkSpec(in *v1alpha3.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_NetworkSpec_To_v1alpha2_NetworkSpec(in, out, s)
}

func autoConvert_v1alpha2_NetworkStatus_To_v1alpha3_NetworkStatus(in *NetworkStatus, out *v1alpha3.NetworkStatus, s conversion.Scope) error {
	out.Connected = in.Connected
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MACAddr = in.MACAddr
	out.NetworkName = in.NetworkName
	return nil
}

// Convert_v1alpha2_NetworkStatus_To_v1alpha3_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha2_NetworkStatus_To_v1alpha3_NetworkStatus(in *NetworkStatus, out *v1alpha3.NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_NetworkStatus_To_v1alpha3_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha3_NetworkStatus_To_v1alpha2_NetworkStatus(in *v1alpha3.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	out.Connected = in.Connected
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MACAddr = in.MACAddr
	out.NetworkName = in.NetworkName
	return nil
}

// Convert_v1alpha3_NetworkStatus_To_v1alpha2_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha3_NetworkStatus_To_v1alpha2_NetworkStatus(in *v1alpha3.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_NetworkStatus_To_v1alpha2_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha2_VSphereCluster_To_v1alpha3_VSphereCluster(in *VSphereCluster, out *v1alpha3.VSphereCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_VSphereClusterSpec_To_v1alpha3_VSphereClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_VSphereClusterStatus_To_v1alpha3_VSphereClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_VSphereCluster_To_v1alpha3_VSphereCluster is an autogenerated conversion function.
func Convert_v1alpha2_VSphereCluster_To_v1alpha3_VSphereCluster(in *VSphereCluster, out *v1alpha3.VSphereCluster, s conversion.Scope) error {
	return autoConvert_v1alpha2_VSphereCluster_To_v1alpha3_VSphereCluster(in, out, s)
}

func autoConvert_v1alpha3_VSphereCluster_To_v1alpha2_VSphereCluster(in *v1alpha3.VSphereCluster, out *VSphereCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_VSphereClusterSpec_To_v1alpha2_VSphereClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_VSphereClusterStatus_To_v1alpha2_VSphereClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_VSphereCluster_To_v1alpha2_VSphereCluster is an autogenerated conversion function.
func Convert_v1alpha3_VSphereCluster_To_v1alpha2_VSphereCluster(in *v1alpha3.VSphereCluster, out *VSphereCluster, s conversion.Scope) error {
	return autoConvert_v1alpha3_VSphereCluster_To_v1alpha2_VSphereCluster(in, out, s)
}

func autoConvert_v1alpha2_VSphereClusterList_To_v1alpha3_VSphereClusterList(in *VSphereClusterList, out *v1alpha3.VSphereClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha3.VSphereCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_VSphereCluster_To_v1alpha3_VSphereCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_VSphereClusterList_To_v1alpha3_VSphereClusterList is an autogenerated conversion function.
func Convert_v1alpha2_VSphereClusterList_To_v1alpha3_VSphereClusterList(in *VSphereClusterList, out *v1alpha3.VSphereClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha2_VSphereClusterList_To_v1alpha3_VSphereClusterList(in, out, s)
}

func autoConvert_v1alpha3_VSphereClusterList_To_v1alpha2_VSphereClusterList(in *v1alpha3.VSphereClusterList, out *VSphereClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VSphereCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_VSphereCluster_To_v1alpha2_VSphereCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_VSphereClusterList_To_v1alpha2_VSphereClusterList is an autogenerated conversion function.
func Convert_v1alpha3_VSphereClusterList_To_v1alpha2_VSphereClusterList(in *v1alpha3.VSphereClusterList, out *VSphereClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha3_VSphereClusterList_To_v1alpha2_VSphereClusterList(in, out, s)
}

func autoConvert_v1alpha2_VSphereClusterSpec_To_v1alpha3_VSphereClusterSpec(in *VSphereClusterSpec, out *v1alpha3.VSphereClusterSpec, s conversion.Scope) error {
	out.Server = in.Server
	out.Insecure = (*bool)(unsafe.Pointer(in.Insecure))
	if err := Convert_v1alpha2_CPIConfig_To_v1alpha3_CPIConfig(&in.CloudProviderConfiguration, &out.CloudProviderConfiguration, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_VSphereClusterSpec_To_v1alpha3_VSphereClusterSpec is an autogenerated conversion function.
func Convert_v1alpha2_VSphereClusterSpec_To_v1alpha3_VSphereClusterSpec(in *VSphereClusterSpec, out *v1alpha3.VSphereClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_VSphereClusterSpec_To_v1alpha3_VSphereClusterSpec(in, out, s)
}

func autoConvert_v1alpha3_VSphereClusterSpec_To_v1alpha2_VSphereClusterSpec(in *v1alpha3.VSphereClusterSpec, out *VSphereClusterSpec, s conversion.Scope) error {
	out.Server = in.Server
	out.Insecure = (*bool)(unsafe.Pointer(in.Insecure))
	// WARNING: in.Thumbprint requires manual conversion: does not exist in peer-type
	if err := Convert_v1alpha3_CPIConfig_To_v1alpha2_CPIConfig(&in.CloudProviderConfiguration, &out.CloudProviderConfiguration, s); err != nil {
		return err
	}
	// WARNING: in.ControlPlaneEndpoint requires manual conversion: does not exist in peer-type
	// WARNING: in.LoadBalancerRef requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha2_VSphereClusterStatus_To_v1alpha3_VSphereClusterStatus(in *VSphereClusterStatus, out *v1alpha3.VSphereClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	// WARNING: in.APIEndpoints requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha3_VSphereClusterStatus_To_v1alpha2_VSphereClusterStatus(in *v1alpha3.VSphereClusterStatus, out *VSphereClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	// WARNING: in.Conditions requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha2_VSphereMachine_To_v1alpha3_VSphereMachine(in *VSphereMachine, out *v1alpha3.VSphereMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_VSphereMachineSpec_To_v1alpha3_VSphereMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_VSphereMachineStatus_To_v1alpha3_VSphereMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_VSphereMachine_To_v1alpha3_VSphereMachine is an autogenerated conversion function.
func Convert_v1alpha2_VSphereMachine_To_v1alpha3_VSphereMachine(in *VSphereMachine, out *v1alpha3.VSphereMachine, s conversion.Scope) error {
	return autoConvert_v1alpha2_VSphereMachine_To_v1alpha3_VSphereMachine(in, out, s)
}

func autoConvert_v1alpha3_VSphereMachine_To_v1alpha2_VSphereMachine(in *v1alpha3.VSphereMachine, out *VSphereMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_VSphereMachineSpec_To_v1alpha2_VSphereMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_VSphereMachineStatus_To_v1alpha2_VSphereMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_VSphereMachine_To_v1alpha2_VSphereMachine is an autogenerated conversion function.
func Convert_v1alpha3_VSphereMachine_To_v1alpha2_VSphereMachine(in *v1alpha3.VSphereMachine, out *VSphereMachine, s conversion.Scope) error {
	return autoConvert_v1alpha3_VSphereMachine_To_v1alpha2_VSphereMachine(in, out, s)
}

func autoConvert_v1alpha2_VSphereMachineList_To_v1alpha3_VSphereMachineList(in *VSphereMachineList, out *v1alpha3.VSphereMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha3.VSphereMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_VSphereMachine_To_v1alpha3_VSphereMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_VSphereMachineList_To_v1alpha3_VSphereMachineList is an autogenerated conversion function.
func Convert_v1alpha2_VSphereMachineList_To_v1alpha3_VSphereMachineList(in *VSphereMachineList, out *v1alpha3.VSphereMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha2_VSphereMachineList_To_v1alpha3_VSphereMachineList(in, out, s)
}

func autoConvert_v1alpha3_VSphereMachineList_To_v1alpha2_VSphereMachineList(in *v1alpha3.VSphereMachineList, out *VSphereMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VSphereMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_VSphereMachine_To_v1alpha2_VSphereMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_VSphereMachineList_To_v1alpha2_VSphereMachineList is an autogenerated conversion function.
func Convert_v1alpha3_VSphereMachineList_To_v1alpha2_VSphereMachineList(in *v1alpha3.VSphereMachineList, out *VSphereMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha3_VSphereMachineList_To_v1alpha2_VSphereMachineList(in, out, s)
}

func autoConvert_v1alpha2_VSphereMachineSpec_To_v1alpha3_VSphereMachineSpec(in *VSphereMachineSpec, out *v1alpha3.VSphereMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	// WARNING: in.Template requires manual conversion: does not exist in peer-type
	// WARNING: in.Datacenter requires manual conversion: does not exist in peer-type
	// WARNING: in.Network requires manual conversion: does not exist in peer-type
	// WARNING: in.NumCPUs requires manual conversion: does not exist in peer-type
	// WARNING: in.NumCoresPerSocket requires manual conversion: does not exist in peer-type
	// WARNING: in.MemoryMiB requires manual conversion: does not exist in peer-type
	// WARNING: in.DiskGiB requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha3_VSphereMachineSpec_To_v1alpha2_VSphereMachineSpec(in *v1alpha3.VSphereMachineSpec, out *VSphereMachineSpec, s conversion.Scope) error {
	// WARNING: in.VirtualMachineCloneSpec requires manual conversion: does not exist in peer-type
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	return nil
}

func autoConvert_v1alpha2_VSphereMachineStatus_To_v1alpha3_VSphereMachineStatus(in *VSphereMachineStatus, out *v1alpha3.VSphereMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]apiv1alpha3.MachineAddress)(unsafe.Pointer(&in.Addresses))
	// WARNING: in.TaskRef requires manual conversion: does not exist in peer-type
	out.Network = *(*[]v1alpha3.NetworkStatus)(unsafe.Pointer(&in.Network))
	// WARNING: in.ErrorReason requires manual conversion: does not exist in peer-type
	// WARNING: in.ErrorMessage requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha3_VSphereMachineStatus_To_v1alpha2_VSphereMachineStatus(in *v1alpha3.VSphereMachineStatus, out *VSphereMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.Network = *(*[]NetworkStatus)(unsafe.Pointer(&in.Network))
	// WARNING: in.FailureReason requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureMessage requires manual conversion: does not exist in peer-type
	// WARNING: in.Conditions requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha2_VSphereMachineTemplate_To_v1alpha3_VSphereMachineTemplate(in *VSphereMachineTemplate, out *v1alpha3.VSphereMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_VSphereMachineTemplateSpec_To_v1alpha3_VSphereMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_VSphereMachineTemplate_To_v1alpha3_VSphereMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha2_VSphereMachineTemplate_To_v1alpha3_VSphereMachineTemplate(in *VSphereMachineTemplate, out *v1alpha3.VSphereMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha2_VSphereMachineTemplate_To_v1alpha3_VSphereMachineTemplate(in, out, s)
}

func autoConvert_v1alpha3_VSphereMachineTemplate_To_v1alpha2_VSphereMachineTemplate(in *v1alpha3.VSphereMachineTemplate, out *VSphereMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_VSphereMachineTemplateSpec_To_v1alpha2_VSphereMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_VSphereMachineTemplate_To_v1alpha2_VSphereMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha3_VSphereMachineTemplate_To_v1alpha2_VSphereMachineTemplate(in *v1alpha3.VSphereMachineTemplate, out *VSphereMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha3_VSphereMachineTemplate_To_v1alpha2_VSphereMachineTemplate(in, out, s)
}

func autoConvert_v1alpha2_VSphereMachineTemplateList_To_v1alpha3_VSphereMachineTemplateList(in *VSphereMachineTemplateList, out *v1alpha3.VSphereMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha3.VSphereMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_VSphereMachineTemplate_To_v1alpha3_VSphereMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_VSphereMachineTemplateList_To_v1alpha3_VSphereMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha2_VSphereMachineTemplateList_To_v1alpha3_VSphereMachineTemplateList(in *VSphereMachineTemplateList, out *v1alpha3.VSphereMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha2_VSphereMachineTemplateList_To_v1alpha3_VSphereMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha3_VSphereMachineTemplateList_To_v1alpha2_VSphereMachineTemplateList(in *v1alpha3.VSphereMachineTemplateList, out *VSphereMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VSphereMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_VSphereMachineTemplate_To_v1alpha2_VSphereMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_VSphereMachineTemplateList_To_v1alpha2_VSphereMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha3_VSphereMachineTemplateList_To_v1alpha2_VSphereMachineTemplateList(in *v1alpha3.VSphereMachineTemplateList, out *VSphereMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha3_VSphereMachineTemplateList_To_v1alpha2_VSphereMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha2_VSphereMachineTemplateResource_To_v1alpha3_VSphereMachineTemplateResource(in *VSphereMachineTemplateResource, out *v1alpha3.VSphereMachineTemplateResource, s conversion.Scope) error {
	// WARNING: in.TypeMeta requires manual conversion: does not exist in peer-type
	// WARNING: in.ObjectMeta requires manual conversion: does not exist in peer-type
	if err := Convert_v1alpha2_VSphereMachineSpec_To_v1alpha3_VSphereMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_VSphereMachineTemplateResource_To_v1alpha2_VSphereMachineTemplateResource(in *v1alpha3.VSphereMachineTemplateResource, out *VSphereMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha3_VSphereMachineSpec_To_v1alpha2_VSphereMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_VSphereMachineTemplateResource_To_v1alpha2_VSphereMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha3_VSphereMachineTemplateResource_To_v1alpha2_VSphereMachineTemplateResource(in *v1alpha3.VSphereMachineTemplateResource, out *VSphereMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha3_VSphereMachineTemplateResource_To_v1alpha2_VSphereMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha2_VSphereMachineTemplateSpec_To_v1alpha3_VSphereMachineTemplateSpec(in *VSphereMachineTemplateSpec, out *v1alpha3.VSphereMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_VSphereMachineTemplateResource_To_v1alpha3_VSphereMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_VSphereMachineTemplateSpec_To_v1alpha3_VSphereMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha2_VSphereMachineTemplateSpec_To_v1alpha3_VSphereMachineTemplateSpec(in *VSphereMachineTemplateSpec, out *v1alpha3.VSphereMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_VSphereMachineTemplateSpec_To_v1alpha3_VSphereMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha3_VSphereMachineTemplateSpec_To_v1alpha2_VSphereMachineTemplateSpec(in *v1alpha3.VSphereMachineTemplateSpec, out *VSphereMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_VSphereMachineTemplateResource_To_v1alpha2_VSphereMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_VSphereMachineTemplateSpec_To_v1alpha2_VSphereMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha3_VSphereMachineTemplateSpec_To_v1alpha2_VSphereMachineTemplateSpec(in *v1alpha3.VSphereMachineTemplateSpec, out *VSphereMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_VSphereMachineTemplateSpec_To_v1alpha2_VSphereMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha2_VirtualMachine_To_v1alpha3_VirtualMachine(in *VirtualMachine, out *v1alpha3.VirtualMachine, s conversion.Scope) error {
	out.Name = in.Name
	out.BiosUUID = in.BiosUUID
	out.State = v1alpha3.VirtualMachineState(in.State)
	out.Network = *(*[]v1alpha3.NetworkStatus)(unsafe.Pointer(&in.Network))
	return nil
}

// Convert_v1alpha2_VirtualMachine_To_v1alpha3_VirtualMachine is an autogenerated conversion function.
func Convert_v1alpha2_VirtualMachine_To_v1alpha3_VirtualMachine(in *VirtualMachine, out *v1alpha3.VirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha2_VirtualMachine_To_v1alpha3_VirtualMachine(in, out, s)
}

func autoConvert_v1alpha3_VirtualMachine_To_v1alpha2_VirtualMachine(in *v1alpha3.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	out.Name = in.Name
	out.BiosUUID = in.BiosUUID
	out.State = VirtualMachineState(in.State)
	out.Network = *(*[]NetworkStatus)(unsafe.Pointer(&in.Network))
	return nil
}

// Convert_v1alpha3_VirtualMachine_To_v1alpha2_VirtualMachine is an autogenerated conversion function.
func Convert_v1alpha3_VirtualMachine_To_v1alpha2_VirtualMachine(in *v1alpha3.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha3_VirtualMachine_To_v1alpha2_VirtualMachine(in, out, s)
}
